const POSTS_PER_PAGE = 7;
const POSTS_TOTAL_LIMIT = 700;

const FEED_PER_PAGE = 7;
const FEED_TOTAL_LIMIT = 700;

const FAVORITES_LIMIT = 5;

export { FAVORITES_LIMIT, FEED_PER_PAGE, FEED_TOTAL_LIMIT, POSTS_PER_PAGE, POSTS_TOTAL_LIMIT };
