const POSTS_PER_PAGE = 7;
const POSTS_TOTAL_LIMIT = 700;

const SEARCH_LIMIT = 10; // max number of search results
const FEED_PER_PAGE = 7;
const FEED_TOTAL_LIMIT = 700;

const FAVORITES_LIMIT = 5;

export {
	POSTS_PER_PAGE,
	POSTS_TOTAL_LIMIT,
	SEARCH_LIMIT,
	FEED_PER_PAGE,
	FEED_TOTAL_LIMIT,
	FAVORITES_LIMIT,
};
